reubeno/brush

brush-interactive/src/interactive_shell.rs
We were previously indiscriminately removing all but the last component of path-like completion results when displaying them for selection (but inserting the full string). We should only do that when we know the completions are supposed to be processed as file paths.
Fixes #75 (completion display of git refs when completing on `git checkout `).
=> fix: don't split completions that aren't file paths

brush-core/src/builtins/exec.rs, brush-core/src/commands.rs, brush-core/src/interp.rs, brush-core/src/openfiles.rs, brush-shell/tests/cases/builtins/read.yaml, brush-shell/tests/cases/here.yaml
Prior to this change, here-documents and here-strings require special handling at command execution time. With this change, we back them with pipes that we write contents into (and then close).
There's risk that the internal pipe buffers fill up before the reading command is executed; to mitigate this, we call `fcntl` to adjust the buffers. That, in turn, brings along a new risk that a very large here-document or here-string will result in a pipe with a very large buffer. We accept that consequence for now, in return for allowing them to be used with a wider variety of commands (e.g., built-in commands). Notably, they can now be used with `read` and we can remove `known_failure` from the corresponding test.
=> feat: rework here doc files

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, brush-core/Cargo.toml, brush-core/src/builtins/mod.rs, brush-core/src/openfiles.rs, brush-interactive/Cargo.toml, brush-parser/Cargo.toml, brush-shell/Cargo.toml, deny.toml
Picking 1.72.0 for now; this required removing usage of a few convenience functions that haven't been around too long, fixing a few minor compilation errors, and downgrading `clap`. When we're ready to move the MSRV higher, we can revert these changes.
=> feat: set + validate intentional MSRV (1.72.0)

Cargo.lock, brush-core/Cargo.toml, brush-interactive/Cargo.toml, brush-parser/Cargo.toml, brush-shell/Cargo.toml
Add `term` feature to the `nix` package dependency of `brush-core`.
=> fix: ensure brush-core builds outside workspace

.github/dependabot.yml, Cargo.lock, brush-core/Cargo.toml
Update `lazy_static` and mark `clap` and `assert_cmd` as ignored in dependabot config for now;
we're on the latest updates of those that we can be without requiring an MSRV update past
`1.72.0`.
=> build: take targeted dependency updates

brush-parser/src/parser.rs, brush-shell/tests/cases/compound_cmds/subshell.yaml
Correct parsing of newlines so that they are strictly required in certain cases of the grammar.
This specifically fixes the case of parsing `(subshell_command)(subshell_command)`. This syntax should not be considered valid, but brush was previously allowing it. This change also adds a test case to confirm.
=> fix: realign newline parsing with spec

brush-parser/src/parser.rs, brush-parser/src/tokenizer.rs
Fix tokenizing of unterminated parameter expansions, command substitutions, and arithmetic expressions. If we ever see end of input, we need to bail.
Also, add tests.
=> fix: correct handling of unterminated expansions

brush-core/src/interp.rs, brush-parser/src/ast.rs, brush-parser/src/parser.rs, brush-parser/src/tokenizer.rs, brush-shell/tests/cases/redirection.yaml
&> is already implemented; this adds the append version of it.
Fixes #102
=> fix: add &>> implementation

brush-core/src/builtins/set.rs, brush-core/src/builtins/shopt.rs, brush-core/src/extendedtests.rs, brush-core/src/namedoptions.rs, brush-core/src/options.rs, brush-core/src/shell.rs, brush-shell/src/main.rs
Enable `-O` and `+O` on the command line to specify shopt-style options.
=> feat: enable -O and +O on command line

Cargo.lock, Cargo.toml, fuzz/.gitignore, fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_target.rs
Initial cargo-fuzz fuzzing target useful for testing tokenizing (and possibly parsing). Thus far has caught ~5 errors in the tokenizer, but needs hand-holding to run.
=> feat: start using cargo-fuzz for testing

Cargo.lock, brush-core/src/shell.rs, brush-parser/Cargo.toml, brush-parser/src/ast.rs, brush-parser/src/tokenizer.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_arithmetic.rs
This paves the way to using fuzz testing for arithmetic evaluation, as well as broader testing with structured brush ASTs.
=> feat: enable fuzz-testing arithmetic eval

brush-core/src/arithmetic.rs, brush-parser/src/arithmetic.rs, brush-parser/src/parser.rs, fuzz/fuzz_targets/fuzz_arithmetic.rs
Fixes a handful of arithmetic evaluation issues discovered through compat fuzz-testing:
* Detect exponentiation with a negative exponent.
* Use `wrapping_` operators rather than panicking on overflow.
* Correct association of exponentiation operator (e.g., is `x ** y ** z` the same as `(x ** y) ** z` or `x ** (y ** z)`).
* Fix parsing of hex values.
=> fix: resolve assorted arithmetic eval issues

Cargo.lock, brush-core/src/arithmetic.rs, brush-core/src/interp.rs, brush-core/src/lib.rs, brush-core/src/options.rs, brush-core/src/shell.rs, brush-shell/src/main.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_arithmetic.rs, fuzz/fuzz_targets/fuzz_parse.rs
Correct overflow behavior for exponentiation (required working around lack of `pow` function that takes a `u64` as the exponent).
Also adds `-n` behavior to the shell.
=> fix: correct ** overflow behavior

Cargo.lock, brush-core/src/builtins/help.rs, brush-core/src/shell.rs, brush-shell/Cargo.toml, brush-shell/src/main.rs, brush-shell/src/productinfo.rs, deny.toml
Include git commit source info in the version displayed by brush; this will help track down which version of sources the binary came from.
=> feat: include more details in version info

.github/workflows/ci.yaml, Cargo.lock, brush-core/Cargo.toml, brush-core/src/builtins/umask.rs, brush-core/src/error.rs, brush-core/src/interp.rs
The fallback is thread unsafe, but it is what other shells are using.
=> feat: Initial support for non-linux

brush-core/src/builtins/umask.rs, brush-core/src/commands.rs, brush-core/src/patterns.rs, brush-parser/src/parser.rs
These warnings haven't been failing PR checks since they're not treated as errors, but should be resolved nonetheless.
=> fix: clippy and check warnings

brush-core/src/builtins/complete.rs, brush-core/src/completion.rs
When a completion spec is found to match the current completion scenario but not completions result, then the correct behavior appears to be to present zero completions. This fixes completion of `cd <path_to_dir_that_contains_no_child_dirs>`.
=> fix: correct completion fallback logic when spec matches but 0 results

brush-core/src/interp.rs, brush-parser/src/ast.rs, brush-parser/src/parser.rs, brush-shell/tests/cases/builtins/read.yaml, brush-shell/tests/cases/redirection.yaml
The prior implementation of process substitution (e.g., `<(command args)`) was a bit confused. This isn't perfect, but should be significantly more accurate. With these changes, `brush`:
* Supports use of `<(command ...)` or `>(command ...)` for any argument to a simple command.
* Supports use of `<(command ...)` or `>(command ...)` as the filename for input or output redirection anywhere those redirections are supported.
* When executing a process substitution command in a subshell, does not synchronously wait for it. (This resolves a known issue with `>(command ...)`.
Also adds more test cases to capture this issue, what's working now, and what is better understood to still differ in behavior. (Notably, bash appears to accept process substitutions in a wider variety of places in its …
=> fix: correct multiple issues with process substitution + redirection

.github/workflows/ci.yaml, scripts/compare-benchmark-results.py
Migrates away from `cargo-binstall` action in favor of using `taiki-e/install-action` more; as a side benefit, this mitigates impact to our actions from https://github.com/cargo-bins/cargo-binstall/issues/1864
While updating the workflow, also:
* Account for error bars in benchmark deltas -- fixes #64
* Sets min requirements for maintaining coverage levels.
=> fix: mitigate build errors setting up cargo-binstall

brush-interactive/src/interactive_shell.rs
When history file updating/creation fails (e.g., the history file path is under a non-existent directory hierarchy) don't fatally error out. This follows bash's behavior to quietly ignore the error and move on without writing out the history lines.
Also adds logic to honor the `histappend` shell option.
Fixes #149
=> fix: make history file creation error non fatal

Cargo.lock, brush-core/Cargo.toml, brush-core/src/shell.rs, brush-interactive/Cargo.toml, brush-interactive/src/basic_shell.rs, brush-interactive/src/error.rs, brush-interactive/src/interactive_shell.rs, brush-interactive/src/lib.rs, brush-interactive/src/rustyline_shell.rs, brush-shell/Cargo.toml, brush-shell/src/args.rs, brush-shell/src/brushctl.rs, brush-shell/src/main.rs, brush-shell/src/shell_factory.rs, brush-shell/tests/cases/builtins/unalias.yaml, xtask/Cargo.toml
Extracts out `InteractiveShell` as a trait, albeit with a few default implementations. (That may be addressed in the future.)
This is intended to pave the way to allow for swapping things out for an alternate implementation experimentally.
=> chore: extract InteractiveShell as trait + refactor

brush-core/src/builtins/complete.rs, brush-core/src/completion.rs
Fixes cases where default completion settings invoke `compgen` and it's given an unexpanded word (e.g., `"~/"`).
=> fix: compgen needs to expand target arg

.vscode/settings.json, brush-core/src/completion.rs
Not the best implementation, but this seems to match what `bash` does and can speed up completion when using debug traps (such as the one that starship installs).
=> fix: do not invoke debug traps during completion funcs

Cargo.lock, brush-shell/Cargo.toml, brush-shell/tests/compat_tests.rs, brush-shell/tests/interactive_tests.rs, deny.toml, docs/how-to/run-tests.md
Update to the latest git commit of `expectrl` and implement a few basic interactive tests covering basic process management (e.g., fg, bg).
=> test: add more basic interactive tests

brush-shell/tests/interactive_tests.rs
These tests are succeeding locally but seem to sometimes(?) fail in GitHub action runs (example: #147). To unblock PRs, I'm going to disable these recent additions until we can sort out what's going on.
=> build: temporarily disable failing test

brush-core/src/builtins.rs, brush-core/src/builtins/echo.rs, brush-shell/src/args.rs, brush-shell/src/main.rs, brush-shell/tests/cases/arguments.yaml, brush-shell/tests/cases/builtins/echo.yaml
Brush misses `--` because of clap's approach to argument parsing. See: [clap-rs/clap/clap_builder/src/parser/parser.rs](https://github.com/clap-rs/clap/blob/edcaf8fcae5b747cee7e70f196d70a49ffcbdb84/clap_builder/src/parser/parser.rs#L103) `if arg_os.is_escape() { ...; continue } // means arg_os == '--'` and `--` is skipped.
But Posix can handle `--` as an operand or a command_name just fine.
```sh
cargo run -- -c 'echo $0: $1 $2 \"$@\"' --  -1 -2
#> CommandLineArgs.script_path = Some('-1')
#> CommandLineArgs.script_args = ['-2']
#> -1: -2 "-2"
bash -c 'echo $0: $1 $2 \"$@\"' --  -1 -2
#> --: -1 -2 "-1 -2"
```
```sh
cargo run -- -c 'echo $0: $1 $2 \"$@\"'  -1 -2
#> error: unexpected argument '-1' found
bash -c 'echo $0: $1 $2 \"$@\"'  -1 -2
#> -1: -2 "-2"
```
```sh
#> echo "$0: $1 $2 …
```
=> fix: Posix compliant argument parsing for `-c` mode

brush-core/src/error.rs, brush-core/src/openfiles.rs, brush-core/src/shell.rs, brush-shell/tests/cases/redirection.yaml
This fixes issues reported when doing something like `source <(some command)`.
=> fix: allow source to be used with process substitution

.config/nextest.toml, .github/workflows/ci.yaml, .gitignore, brush-core/src/commands.rs, brush-core/src/interp.rs, brush-shell/tests/cases/basic.yaml, brush-shell/tests/cases/builtins/alias.yaml, brush-shell/tests/cases/builtins/shopt.yaml, brush-shell/tests/cases/builtins/unalias.yaml, brush-shell/tests/cases/interactive.yaml, brush-shell/tests/cases/word_expansion.yaml, brush-shell/tests/compat_tests.rs, brush-shell/tests/interactive_tests.rs
Switches CI actions to use `cargo nextest` instead of `cargo test`. This required some changes to interactive tests that fail under `nextest`. A few tests were disabled to get this change in place; they'll need to be revisited subsequently.
Also shifted toward having the PR and CI tests use a recent, stable version of `bash` installed via Homebrew. That ensures consistency across the macOS and Linux tests, and somewhat insulates from any staleness of the system `bash` installed in the runner VM.
=> test: move to cargo nextest

.config/nextest.toml, brush-shell/tests/cases/builtins/shopt.yaml, brush-shell/tests/cases/builtins/trap.yaml, brush-shell/tests/cases/builtins/unset.yaml, brush-shell/tests/cases/here.yaml, brush-shell/tests/cases/options.yaml, brush-shell/tests/cases/redirection.yaml, brush-shell/tests/cases/word_expansion.yaml
Some of the tests previously being skipped could be run under `cargo nextest` in our compat test harness's "pty mode" instead. Some still fail, but at least they can be run and show up as known failures.
=> test: convert more test skips to known failures

Cargo.lock, brush-shell/Cargo.toml, brush-shell/tests/cases/builtins/shopt.yaml, brush-shell/tests/cases/word_expansion.yaml, brush-shell/tests/compat_tests.rs
This enables us to tag certain tests as only being applicable when a given minimum version of the oracle (i.e., `bash`) is installed on the test system. This is practically useful since we now have a few tests that pass when comparing `brush` to `bash` only when `bash` is `>= 5.2`.
=> test: enable setting min oracle version on tests

brush-parser/src/parser.rs, brush-shell/tests/cases/extended_tests.yaml
Newlines can appear right after the `[[` or right before the `]]`, as well as around `&&` and `||` operators.
=> fix: allow newlines in extended test exprs

brush-core/src/builtins/complete.rs, brush-core/src/builtins/printf.rs, brush-core/src/builtins/read.rs, brush-core/src/completion.rs, brush-core/src/error.rs, brush-core/src/interp.rs, brush-core/src/lib.rs, brush-core/src/patterns.rs, brush-core/src/regex.rs, brush-core/src/shell.rs, brush-parser/src/ast.rs, brush-parser/src/lib.rs, brush-parser/src/pattern.rs, brush-shell/tests/cases/arrays.yaml, brush-shell/tests/cases/builtins/compgen.yaml, brush-shell/tests/cases/builtins/printf.yaml, brush-shell/tests/compat_tests.rs, brush-shell/tests/completion_tests.rs
* Correct `compgen` handling of positional args that start with a hyphen
* Correct `printf` handling of `-v` in a format argument.
* Fix bug with stale `REPLY` value in `read` of an empty line
* Correct handling of Ctrl+D in `read`
* Fix missing terminal setting restoration on Ctrl+C in `read`
* Support completing a line that fails tokenization
* Fix use of `declare` to assign an array from the split expansion of a variable
* Fix escaping of `[` char in a character class in a pattern
* Clean up skipping logic in compat tests harness
* Add some basic tests for completion via `brushinfo complete`
=> feat: several fixes for bash-completion + tests

brush-core/src/error.rs, brush-core/src/expansion.rs, brush-core/src/interp.rs, brush-interactive/src/completion.rs, brush-parser/src/word.rs, brush-shell/tests/cases/and_or.yaml, brush-shell/tests/cases/compound_cmds/for.yaml, brush-shell/tests/cases/compound_cmds/while.yaml, brush-shell/tests/cases/extended_tests.yaml, brush-shell/tests/cases/word_expansion.yaml
* Correct short-circuiting of `&&` / `||` in mixed chains
* Enable `${var//pattern}` without a specified replacement
* Enable `break` to be used in an and-or list
* Add tests for corrected functionality
=> fix: fixes for short-circuit precedence + parameter expr replacement

brush-core/src/patterns.rs, brush-interactive/src/reedline/completer.rs, brush-interactive/src/reedline/reedline_shell.rs, brush-parser/src/word.rs, brush-shell/tests/cases/extended_tests.yaml, brush-shell/tests/cases/word_expansion.yaml
* Fixes 'Binary string matching with expansion' test case
* Adds + fixes 'Command substitution with embedded parens' test case
=> fix: workarounds for edge word parsing cases

.config/nextest.toml, brush-core/src/builtins/complete.rs, brush-core/src/builtins/echo.rs, brush-core/src/builtins/printf.rs, brush-core/src/commands.rs, brush-core/src/completion.rs, brush-core/src/escape.rs, brush-core/src/expansion.rs, brush-core/src/interp.rs, brush-core/src/patterns.rs, brush-core/src/trace_categories.rs, brush-parser/src/arithmetic.rs, brush-parser/src/parser.rs, brush-parser/src/word.rs, brush-shell/src/events.rs, brush-shell/tests/cases/builtins/compgen.yaml, brush-shell/tests/cases/builtins/printf.yaml, brush-shell/tests/cases/extended_tests.yaml, brush-shell/tests/cases/word_expansion.yaml, brush-shell/tests/compat_tests.rs, brush-shell/tests/completion_tests.rs
Adds 5 new automated test cases for completion + gets them (mostly) passing:
* Completion under an empty dir
* Completion of a non-existent relative path
* Complete absolute file paths
* Complete file path containing variable (e.g., `$HOME`)
* Complete file path containing `~`
_(Note that we needed to leave 2 tests temporarily disabled as they pass only on certain versions of `bash-completion`. Rather than further complicate the PR; we will address them separately.)_
This entailed:
* Propagating exit results from failed command substitution through to assignments that depend on it.
* Targeted compatibility fix for limited set of `printf %q` cases
* Return 1 from `compgen` when no completions were generated
* Only filtering completions based on the token-being-completed for …
=> fix: assorted completion issues with ~ and vars

brush-core/src/escape.rs, brush-core/src/extendedtests.rs, brush-core/src/variables.rs, brush-shell/tests/cases/options.yaml
Does a better job of single-quoting words that need it in simple commands (and some cases of extended test expressions.
=> fix: slight compat improvements to set -x

brush-core/src/builtins/help.rs, brush-core/src/completion.rs, brush-core/src/expansion.rs, brush-core/src/extendedtests.rs, brush-core/src/interp.rs, brush-core/src/patterns.rs, brush-core/src/shell.rs, brush-shell/tests/cases/compound_cmds/case.yaml
* Enables glob patterns to match against newline chars using regex `(?ms)` options.
* Adopts builder pattern for `Pattern` struct, primarily for configuring options (e.g., multiline match support, extglob support).
* Cleans up pattern handling code to remove duplicate logic.
* Adds test case ensuring `case` patterns work correctly against a multiline string.
=> fix: matching newline chars in glob patterns

brush-core/src/builtins/read.rs, brush-shell/tests/cases/builtins/read.yaml
Ensure that splitting happening in `read` honors the current effective value of `IFS` in the current environment.
Among other things, this fixes completion for arguments to `tar`. (The custom completion routines for `tar` in `bash-completion` do custom parsing of the `--help` output of `tar`; that parsing required `read`ing in that output and using complex regexes to match against it.)
=> fix: honor IFS in read builtin

brush-core/src/builtins/unset.rs, brush-parser/src/word.rs, brush-shell/tests/cases/arrays.yaml, brush-shell/tests/cases/builtins/unset.yaml
Also address parse issues with complex array index expressions.
=> fix: address issues with array unset

brush-interactive/src/reedline/completer.rs
In the future we can simplify this (rather than having to postprocess the candidates), but this is a more targeted fix that works for now without a bit of refactoring.
=> fix: leave trailing whitespace out of reedline completion suggestions

brush-core/src/builtins.rs, brush-core/src/interp.rs, brush-core/src/patterns.rs, brush-interactive/src/interactive_shell.rs, brush-parser/src/ast.rs, brush-parser/src/parser.rs, brush-parser/src/tokenizer.rs, brush-shell/tests/cases/compound_cmds/case.yaml
Implements support for bash extensions to case item terminators: `;;&` and `;&`.
Fixes one of the issues tracked by #222.
=> feat: implement support for ;;& and ;& in case items

brush-parser/src/parser.rs, brush-shell/tests/cases/extended_tests.yaml
In an extended test command, the following example regex is not allowed:
```
[[ str =~ < ]]
```
But if it's placed in parentheses, it *is* allowed:
```
[[ str =~ (<) ]]
```
These changes relax our parser's restrictions on which tokens typically parsed as operators may be allowed in that context. We add a compat test case to confirm.
=> fix: allow usually-operator chars in regex parens

brush-core/src/builtins/getopts.rs, brush-shell/tests/cases/builtins/getopts.yaml
The `getopts` builtin wasn't handling a handful of cases correctly.
Addresses one of the issues encountered while debugging #222.
=> fix: assorted correctness issues in getopts builtin

brush-core/src/builtins/complete.rs, brush-core/src/builtins/getopts.rs, brush-core/src/builtins/printf.rs, brush-core/src/completion.rs, brush-core/src/shell.rs, brush-parser/src/lib.rs, brush-parser/src/tokenizer.rs, brush-shell/tests/cases/arrays.yaml, brush-shell/tests/cases/builtins/compgen.yaml, brush-shell/tests/cases/builtins/getopts.yaml, brush-shell/tests/cases/builtins/printf.yaml, brush-shell/tests/completion_tests.rs
* Unquote the token-to-be-completed passed into `compgen`
* Support multiple-options-in-one-token in `getopts` (e.g., `-abc` as shorthand for `-a` `-b` `-c`)
* Initialize `OPTIND`, `OPTERR` in each newly constructed shell.
* Fix bug in `printf` hack for `%q` and `~%q`.
* Don't filter out file/dir completions whose prefixes don't match the token-being-completed (e.g., for `~` et al.).
* For file/dir completions, basic-expand the token-to-be-completed (we formerly did this higher up the stack).
* Express compatibility with a slightly newer version of `bash` (5.2.x).
* Re-enable some previously disabled tests.
=> fix: assorted completion-related issues

brush-parser/src/word.rs, brush-shell/tests/cases/arrays.yaml, brush-shell/tests/cases/word_expansion.yaml
Fixes the case where a string replacement contains `/` chars, e.g.:
```bash
${value/pattern/some/replacement}
```
=> fix: string replacement with slashes

brush-core/src/expansion.rs, brush-shell/tests/cases/word_expansion.yaml
This was missed when the other expansions were retrofitted to support arrays; uses existing `transform_expansion` helper to simplify the work of iteratively transforming all elements of the array.
=> fix: correct pattern removal expansions on arrays

brush-core/src/builtins/getopts.rs, brush-shell/tests/cases/builtins/getopts.yaml
* Apply the same workaround to `getopts` that was added for `echo` in #147.
* Add a test case to cover `--` being passed as the first arg to `getopts` after the variable name.
=> fix(completion): fix -- handling in getopts

brush-core/src/shell.rs
We were already filtering on executables, but forgot to filter on being a _file_. Among other things, this fixed an issue spotted in completion of help topics.
=> fix: omit dirs from executable searches

brush-core/src/expansion.rs, brush-shell/tests/cases/word_expansion.yaml
When using the substring/slice operator past the end of an array, make sure not to yield an empty string.
=> fix(completion): correct behavior of slice past end of array

.github/workflows/ci.yaml, brush-shell/Cargo.toml, brush-shell/tests/completion_tests.rs
* Enable running completion tests using an alternate installation of `bash-completion` (via `BASH_COMPLETION_PATH` variable)
* Add another relatively simple completion test
* Update CI workflow to download `bash-completion` v2.14.0 and run `brush-completion-tests` with it
=> test: run completion tests using bash-completion 2.14.0

brush-core/src/shell.rs, brush-interactive/src/interactive_shell.rs
Tools like [starship](https://starship.rs) customize `PS2` in addition to `PS1`; the same logic used to expand and evaluate `PS1` should apply to `PS2` as well.
=> fix: handle PS2 prompts that require prompt-expansion

.github/workflows/ci.yaml, brush-core/src/shell.rs, brush-shell/Cargo.toml, brush-shell/src/args.rs, brush-shell/src/main.rs, brush-shell/tests/cases/builtins/command.yaml, brush-shell/tests/compat_tests.rs, brush-shell/tests/completion_tests.rs, brush-shell/tests/interactive_tests.rs
For increased integration coverage, add new jobs that take the produced Linux/x86_64 release binaries and use them to run our compatibility and completion integration tests on each of Fedora, Debian, and Arch Linux.
In the future, we'll want to enable interactive tests and evaluate which other target platforms are appropriate for additional testing.
=> test: add os-targeted integration tests

brush-core/src/builtins/kill.rs, brush-core/src/builtins/trap.rs, brush-core/src/completion.rs, brush-core/src/error.rs, brush-core/src/sys/stubs/signal.rs, brush-core/src/sys/unix/signal.rs, brush-core/src/traps.rs, brush-shell/tests/cases/builtins/kill.yaml
Utilize `nix::signal::Signal` to print the all signals.
Note that `0 - EXIT` is missing for now because it is not posix, and I didn't find any documentation for the `EXIT` signal, except for the `trap` builtin https://www.gnu.org/software/bash/manual/html_node/Bourne-Shell-Builtins.html
> If a sigspec is 0 or EXIT, arg is executed when the shell exits.
=> feat: implement `kill -l`

Cargo.lock, brush-core/Cargo.toml, brush-interactive/Cargo.toml, brush-parser/Cargo.toml, brush-shell/Cargo.toml, fuzz/Cargo.toml, xtask/Cargo.toml
* `async-recursion` => 1.1.1
* `cached` => 0.53.1
* `clap` => 4.5.20
* `fancy-regex` => 0.14.0
* `thiserror` => 1.0.65
* `tokio` => 1.41.0
* `homedir` => 0.3.4
* `anyhow` => 1.0.91
* `assert_cmd` => 2.0.16
* `assert_fs` => 1.1.2
* `regex` => 1.11.1
* `serde` => 1.0.213
=> chore: upgrade crate dependencies

.github/workflows/docs.yaml
We run in `--offline` mode to avoid network traffic originated by potentially untrusted content.
=> build: run lychee to check intra-repo links in action

.github/workflows/ci.yaml
Checks for unneeded dependencies in the project's crates.
=> build: run cargo udeps in checks

.github/workflows/docs.yaml
Generate and upload command-line usage docs (markdown, man) in actions.
=> docs: generate usage docs in actions via xtask

brush-parser/src/parser.rs, brush-shell/tests/cases/pipeline.yaml
Closed: #242 
WIP. Adding `|&` for function declarations turns out to be quite straightforward. However `extended tests` require some move work
=> feat: implement `|&` for function declarations

Cargo.lock, brush-core/src/shell.rs, brush-parser/Cargo.toml, brush-parser/src/parser.rs, brush-parser/src/tokenizer.rs, brush-shell/tests/cases/here.yaml
The main challenge that we've encountered here is that tokenization of a here-document in `brush` has previously not included *all* pieces of the original input; notably it omitted yielding the matching closing tag, since it was not strictly needed by the parser. While testing these changes, we found deeper challenges with empty here-documents and multiple here-documents (potentially mixed with non-redirection tokens on the initial command line).
While there is opportunity to improve this in the future, the main design we're going with:
* Tokenizer reorders tokens so that the redirection operation, start here tag, here document body, and end here tag are consecutive. This simplifies life for the parser so it doesn't need to maintain a FIFO-based here tag state, which would be tricky to do …
=> fix: support here documents in command substitutions

brush-parser/src/ast.rs, brush-parser/src/parser.rs
#254
Instead of using `insta` with text representation we can actually use `assert_eq!` with a direct snapshot of the data structure. I've added one example `parser::tests::test_parse_program`to show how it looks like. 
The `#[derive]` only applies when `cfg_attr(test)` is enabled.
- simple
- no external tools needed
- rust-analyzer can rename fields
- syntax highlighting/formatting
=> feat(ast): derive `PartialEq` and `Eq` for testing

brush-parser/src/parser.rs, brush-shell/tests/cases/compound_cmds/arithmetic.yaml
Among other things, fixes the case of `(( (0) != 1 ))`.
=> fix: correct parsing of parens in arithmetic command

brush-core/src/expansion.rs, brush-core/src/shell.rs, brush-core/src/variables.rs, brush-shell/tests/cases/arrays.yaml, brush-shell/tests/cases/variables.yaml
Enables appending scalar values to declared but uninitialized variables. 
Fixes concatenation of array values with non-default IFS values.
=> fix: multiple issues blocking docker cmd completion

brush-core/src/expansion.rs, brush-shell/tests/cases/patterns.yaml
Adds tests for `noglob` and `nullglob` options; makes sure both work.
Resolves #229
=> feat(set): implement nullglob option

brush-core/src/expansion.rs, brush-parser/src/word.rs, brush-shell/tests/cases/word_expansion.yaml, brush-shell/tests/compat_tests.rs
There is more to understand with respect to differences from `bash`'s output, but with this change `brush` no longer generates an error when trying to slice into a string somewhere other than at a character boundary.
=> fix: improve substring ops with multi-byte chars

README.md, brush-core/src/expansion.rs, brush-core/src/extendedtests.rs, brush-parser/src/error.rs, brush-parser/src/word.rs, brush-shell/tests/cases/extended_tests.yaml, brush-shell/tests/cases/word_expansion.yaml
This covers one of the last big remaining holes in expansion (the other is history expansion), albeit with complexity.
Resolves #42
=> feat: implement brace expansion

brush-core/src/interp.rs, brush-core/src/options.rs, brush-core/src/shell.rs, brush-shell/src/args.rs, brush-shell/src/main.rs, brush-shell/tests/cases/options.yaml
* Adds support for `-C` on command line, via `set`, etc.
* Adds basic compat tests to check.
=> feat(options): implement noclobber option (a.k.a. -C)

.github/workflows/ci-reports.yaml, .github/workflows/ci.yaml, .github/workflows/devcontainer.yaml, .github/workflows/docs.yaml
`ubuntu-latest` is going to get upgraded to `ubuntu-24.04` shortly, but we'd rather intentionally upgrade and work through any issues rather than having them "show up one day".
This PR pins all workflows to`ubuntu-24.04` with the one notable exception of the native x86_64/Linux build, which we pin to `ubuntu-22.04`. We do this intentionally because 24.04 brings in a newer version of `glibc` and decreased compatibility for produced rust binaries.
=> chore: pin workflows to specific ubuntu versions

Cargo.lock, brush-core/Cargo.toml, brush-core/benches/shell.rs, brush-core/src/prompt.rs, brush-parser/src/prompt.rs, brush-shell/tests/cases/prompt.yaml
Fills out implementation and adds tests for the follow escape sequences in prompt strings:
* `\d`
* `\D`
* `\t`
* `\T`
* `\@`
=> fix: implement date and time in prompts

brush-core/src/completion.rs, brush-interactive/src/completion.rs, brush-shell/tests/cases/builtins/compgen.yaml, brush-shell/tests/cases/builtins/complete.yaml
* Fills out handling of `default`, `dirnames`, and `plusdirs` options for completion.
* Adds a few basic compat tests for this logic.
Notably, this makes `git diff -- <start_of_file_path>` complete to something sensibly.
=> fix(completion): handle -o {default,dirnames,plusdirs}

brush-core/benches/shell.rs, brush-shell/Cargo.toml
This makes no changes to the code-under-analysis; the perf deltas that show in the PR report are due to the changes in the definitions of the benchmarks.
=> perf: remove setup operations from microbenchmarks

brush-core/Cargo.toml, brush-core/src/builtins.rs, brush-core/src/builtins/factory.rs, brush-core/src/builtins/times.rs, brush-shell/tests/cases/builtins/times.yaml
Implement the `times` builtin, but only on Unix-based platforms (i.e., Linux, macOS). We're relying on `nix` and its wrapper for `getrusage` as implementation.
=> feat(builtins): implement times builtin

brush-core/src/builtins.rs, brush-core/src/builtins/factory.rs, brush-core/src/builtins/times.rs, brush-core/src/error.rs, brush-core/src/interp.rs, brush-core/src/keywords.rs, brush-core/src/lib.rs, brush-core/src/sys.rs, brush-core/src/sys/stubs.rs, brush-core/src/sys/stubs/resource.rs, brush-core/src/sys/unix.rs, brush-core/src/sys/unix/resource.rs, brush-core/src/sys/wasm.rs, brush-core/src/sys/windows.rs, brush-core/src/timing.rs, brush-parser/src/ast.rs, brush-parser/src/parser.rs
This implements `time`, which in the bash world is a special keyword usable at the beginning of pipelines--not a built-in.
=> feat(non-posix): implement `time` keyword

.cargo/config.toml, Cargo.toml
* Tell `rustc` to target the CPU that it's running on; this brings the trade-off that compiled binaries may not be appropriate for execution on arbitrary target systems. For now, we're okay with that since we don't publish binaries. We may need to revisit this in the future.
* Set lto setting to `fat`
* Configure panicking on abort (no unwinding)
=> perf: adjust compile flags for runtime performance

brush-core/src/expansion.rs, brush-shell/tests/cases/word_expansion.yaml
Among other things, this fixes some issues with completion for `strace` command lines.
=> fix(expansion): correct length for 1-element arrays

brush-core/src/builtins/complete.rs, brush-core/src/completion.rs, brush-core/src/patterns.rs, brush-parser/src/pattern.rs, brush-shell/tests/cases/builtins/compgen.yaml, brush-shell/tests/cases/patterns.yaml, brush-shell/tests/completion_tests.rs
Fixes multiple issues with extglob pattern matching support, particularly with `!(...)` patterns. Additional changes for use of patterns as filter expressions in completion (notably, fixes to inversion).
* [`brush-parser/src/pattern.rs`](diffhunk://#diff-6d3d15c993f8181f7e8182d68c72fca77a48114f71a359773d73da6745bff401L95-R107): Refactored the `extended_glob_body` rule to simplify the parsing of extended glob patterns and adjusted how negative lookaheads are handled in the regex generation. [[1]](diffhunk://#diff-6d3d15c993f8181f7e8182d68c72fca77a48114f71a359773d73da6745bff401L95-R107) [[2]](diffhunk://#diff-6d3d15c993f8181f7e8182d68c72fca77a48114f71a359773d73da6745bff401L111-L113) [[3]](diffhunk://#diff-6d3d15c993f8181f7e8182d68c72fca77a48114f71a359773d73da6745bff401L127-R135)
* …
=> fix: correct issues with `!` extglobs and compgen -X

brush-core/src/completion.rs, brush-parser/src/pattern.rs, brush-shell/tests/cases/patterns.yaml
* Don't allow an unescaped `']'` to be treated as the end range of a character range. This fixes patterns using, for example, `[+-]`.
* Allow either `^` or `!` to invert a character set.
* Make it easier to debug internal errors showing up during completion attempts.
=> fix(patterns): fix incorrect parse of char ranges

brush-core/src/arithmetic.rs, brush-core/src/expansion.rs, brush-core/src/extendedtests.rs, brush-core/src/interp.rs
When we have a string that needs to be interpreted as an unexpanded arithmetic expression, there's no reason to wrap it in a struct that insists on an owned copy; we can directly pass through the `&str` to the core logic that's performing expansion and evaluation.
=> chore: remove unneeded string cloning for arithmetic eval

brush-interactive/src/basic/term_line_reader.rs
When displaying file completions that contain path separators, only show the final path component.
=> fix(completion): improve basic backend completion output

.vscode/launch.json, Cargo.lock, brush-shell/tests/cases/assignments.yaml, brush-shell/tests/cases/builtins/compgen.yaml, brush-shell/tests/cases/patterns/filename_expansion.yaml, brush-shell/tests/cases/patterns/patterns.yaml, brush-shell/tests/cases/word_expansion.yaml, docs/demos/demo.tape
* Add a few new tests to track recently reported issues; mark them as being known to fail for now.
* Slightly regroup the pattern tests, dividing them into filename expansion using patterns vs. pattern matching.
* Add a test case for tilde-expansion in assignments.
* Add a `launch.json` for more easily debugging brush in VS Code.
* Add a sample VHS-style transcript for generating scripted screen caps.
=> chore: test updates

brush-core/src/completion.rs, brush-core/src/expansion.rs, brush-core/src/patterns.rs, brush-core/src/shell.rs, brush-shell/tests/cases/patterns/filename_expansion.yaml
Ensures that filename expansion complies with `dotglob` option setting. The tests added are marked for bash 5.2+ as the oracle, since we're seeing different results from earlier versions of bash related to enumeration of `.` and `..`.
Resolves #328
=> feat(options): implement dotglob semantics

.github/workflows/ci.yaml
Switch to using the new GitHub-provided arm64 runners (using Ubuntu 24.04). 
Now that we're able to, also enable unit test execution on aarch64/Linux. 
Note we needed to skip homebrew usage on this platform, since it's not supported.
=> chore: adopt native arm64 github runners

brush-core/src/interp.rs, brush-shell/tests/cases/compound_cmds/for.yaml
When `in` is not specified with a `for` clause, we need to enumerate positional arguments instead (i.e., $@).
This scenario was getting parsed correctly, but not correctly interpreted.
Resolves #342. Thanks to @ko1nksm for identifying the problem and filing a bug report on it!
=> fix(for): correct semantics for "for" without "in"

brush-core/src/extendedtests.rs, brush-parser/src/ast.rs, brush-parser/src/test_command.rs, brush-shell/tests/cases/builtins/test.yaml
In a non-extended test command (e.g., `[` or `test`), the `=`, `==`, and `!=` operators are direct, case-sensitive string comparisons -- with no pattern matching. These changes correct that behavior.
(The incorrect behavior was inadvertently inherited from `[[`-style extended test commands when originally implemented.)
Resolves #340. Thanks to @ko1nksm for identifying the problem and filing a bug report on it!
=> fix: correct semantics of = in non-extended test commands

.github/workflows/ci.yaml
We've been running into internal compiler errors compiling for arm64 since #335 . For now, we'll revert most of that change to unblock other work.
=> build: partially revert recent arm64 changes

brush-core/src/arithmetic.rs, brush-shell/tests/cases/arithmetic.yaml
In an arithmetic expression, we need to recursively parse and evaluate the body of any bare variable references.
Resolves #345.
=> fix(arithmetic): recursively evaluate var references

brush-parser/Cargo.toml, brush-parser/src/word.rs, brush-shell/tests/cases/arithmetic.yaml
* Fixes parsing of certain cases of nested parenthetical expressions in arithmetic
* Adds compat tests and unit tests for arithmetic parsing of these and similar cases
* Adds new feature flag (`"debug-tracing"`) to the `brush-parser` crate for debugging the rust-peg based parsers; supports integration with `pegviz` for easier visualization.
Resolves #343
=> fix(arithmetic): fixes for nested parenthesis parsing in arithmetic

brush-core/src/builtins/set.rs, brush-shell/tests/cases/builtins/set.yaml
Addresses issues with `set` builtin's handling of `-` and `--`. This required applying the same `--` parsing workaround to the `set` builtin implementation that was previously applied to `echo`.
Resolves #339.
=> fix(builtins): fix set builtin handling of - and --

README.md, brush-core/src/builtins/command.rs, brush-shell/tests/cases/builtins/command.yaml
Also simplifies the logic a bit and corrects handling of `command` invoked with no arguments.
Resolves #344
=> fix(builtins): do not interpret --help in command builtin command args

README.md, brush-core/src/arithmetic.rs, brush-core/src/builtins.rs, brush-core/src/builtins/set.rs, brush-core/src/builtins/unset.rs, brush-core/src/jobs.rs, brush-shell/tests/cases/builtins/set.yaml
@ko1nksm noticed that #354 left behind some incorrect behavior with positional arguments to the `set` builtin that had `+` as a prefix. This PR mitigates that issue while leaving the original issue in #339 covered.
Unfortunately, this is getting us more into hand-parsing arguments for the `set` builtin, but it appears unavoidable for now. The right long-term option still seems to be working with the `clap-rs` community to properly support customizable semantics for `--`, support for `+` short-name options, etc.
Resolves #339.
=> fix(builtins): correct more 'set' argument parsing

brush-parser/src/parser.rs, brush-shell/tests/cases/redirection.yaml, brush-shell/tests/compat_tests.rs
Use token location information to confirm that the optional file descriptor that precedes a redirection operator wasn't separated by space that's since been elided by tokenization.
Also adds more tests for redirection and extends the compat test harness to display the actual diff between temp files found to differ.
(Contributes to one of the root causes of #358.)
=> fix(redirection): make sure redirection fd + operator are contiguous

Cargo.lock, README.md, brush-core/src/arithmetic.rs, brush-core/src/builtins/cd.rs, brush-core/src/builtins/declare.rs, brush-core/src/builtins/export.rs, brush-core/src/builtins/getopts.rs, brush-core/src/builtins/set.rs, brush-core/src/commands.rs, brush-core/src/env.rs, brush-core/src/expansion.rs, brush-core/src/interp.rs, brush-core/src/options.rs, brush-core/src/pathcache.rs, brush-core/src/shell.rs, brush-core/src/sys/stubs/users.rs, brush-core/src/sys/unix/users.rs, brush-core/src/sys/windows/users.rs, brush-core/src/variables.rs, brush-interactive/src/interactive_shell.rs, brush-shell/tests/cases/basic.yaml, brush-shell/tests/cases/status.yaml, brush-shell/tests/cases/well_known_vars.yaml
Implements the ideas in #233, with `$RANDOM` as an initial case. The main downside here is requiring that a `&Shell` be passed into various `ShellVariable` functions
Adds various other standard variables that are now easier for us to implement and keep in sync with fields in the `Shell` object.
Notably, this lacks support for handling mutation of these dynamic values. We'll need to implement this in the future.
=> feat(env): introduce dynamic vars backed by rust code

brush-core/src/commands.rs, brush-shell/tests/cases/simple_commands.yaml
For now, we focus on improving the error messages. We considered falling back to using an alternate working directory when we detect that the CWD is no longer present, but any dir we pick could be problematic. (Consider the idea of `rm -rf ..` being invoked and us running it in some fallback dir.)
Addresses #366
=> fix: better error when cwd is gone

brush-core/src/builtins/read.rs, brush-shell/tests/cases/builtins/read.yaml
Some ASCII whitespace characters (e.g., `\t`) are also considered control characters. Don't ignore *all* of them in `read`.
=> fix(builtins): fix read builtin ignoring tab chars

brush-core/src/completion.rs
This should hopefully make it quicker to track down completion errors in the future. It should also allow completion to degrade a bit more gracefully in this case.
=> fix(completion): better handle native errors in completion funcs

brush-core/benches/shell.rs, brush-core/src/arithmetic.rs, brush-core/src/builtins/printf.rs, brush-core/src/builtins/test.rs, brush-core/src/commands.rs, brush-core/src/completion.rs, brush-core/src/expansion.rs, brush-core/src/extendedtests.rs, brush-core/src/interp.rs, brush-core/src/shell.rs, brush-core/src/tests.rs, brush-shell/tests/cases/redirection.yaml
Address cases where command substitution environments don't correctly inherit the open files of the containing command.
_Caveat: I'm not thrilled about how much code needed to be touched, but this at least *fixes* a known defect. Hopefully we can clean it up subsequently._
=> fix: propagate execution parameters more thoroughly

brush-core/src/builtins/mapfile.rs, brush-core/src/builtins/read.rs, brush-core/src/commands.rs, brush-core/src/interp.rs, brush-shell/tests/cases/redirection.yaml
Redirection failure is an error that will cause the command to fail, but subsequent commands in a compound command, say, should be executed normally.
Resolves #341.
=> fix(redirection): allow continuing past redir errors

brush-core/src/shell.rs, brush-shell/tests/cases/well_known_vars.yaml
There are new warnings from deprecated rng functions; this fixes those warnings and adds some *extremely minimal* coverage of `$RANDOM` and `$SRANDOM` in the compat tests.
=> chore: fix rng warnings

.github/workflows/ci.yaml, scripts/summarize-pytest-results.py
For additional data points of compatibility, we're starting to run the test suite from the [bash-completion](https://github.com/scop/bash-completion) project as part of our PR/CI flow. We won't gate on a certain result level, at least not for now, but we'll start paying attention to pass rates.
=> test: run bash-completion tests

README.md, brush-core/src/builtins/set.rs
Brings pass rate of bash completion test suite to 60+%.
=> test: resolve false errors about side effects in bash-completion tests

brush-core/src/builtins/bind.rs
`bind` is still largely unimplemented, but this at least improves the error messages it emits when a caller provides a key sequence as a positional argument.
Found by #380
=> fix(builtins): correct parsing of bind positional arg

brush-core/src/builtins/exec.rs, brush-core/src/shell.rs, brush-shell/tests/cases/builtins/exec.yaml
Resolves #383 
Thankfully, this was a simple fix. The `exec` builtin was missing logic to handle file descriptor inheritance in the command-less case, i.e., that the open files set up for the builtin need to be *persistently* propagated back to the running shell.
Adds a new test case that easily reproduced the reported issue, and now confirms it's fixed.
=> fix(builtins): implement command-less exec semantics with open fds

brush-core/src/builtins/complete.rs, brush-core/src/builtins/export.rs, brush-core/src/builtins/read.rs, brush-core/src/commands.rs, brush-core/src/completion.rs, brush-core/src/escape.rs, brush-core/src/expansion.rs, brush-core/src/extendedtests.rs, brush-core/src/variables.rs, brush-shell/tests/cases/builtins/declare.yaml, brush-shell/tests/cases/builtins/read.yaml
* Adds a handful of compat test cases for `read`, with a specific focus on IFS handling and `-d` handling.
* Fixes multiple issues with `read` to get tests to pass; notably, implementing support for `-d ''` (i.e., empty delimiter) and correcting semantics with how IFS space characters delimit.
* Along the way, corrected discrepancies with how `declare` et al. format certain strings (e.g., upgrading to ANSI-C quoting when the string includes control characters, including newlines).
=> fix(builtins): correct read handling of IFS/space

brush-parser/src/pattern.rs, brush-shell/tests/cases/builtins/declare.yaml, brush-shell/tests/cases/builtins/read.yaml, brush-shell/tests/cases/patterns/filename_expansion.yaml
Corrects parsing of `extglob` patterns such as `@(|text)`.
=> fix(extglob): correct handling of extglobs with empty branches

brush-parser/src/arithmetic.rs, brush-shell/tests/cases/arithmetic.yaml
Implements support for arithmetic literals like `2#1010` and `16#32f`.
The native Rust facility to parsing integers with an explicit radix only supports base 2-36. That's pretty reasonable, but `bash` technically supports up through base 64. For now, we do our best with the native facilities.
=> feat(arithmetic): support explicit base#literal in arithmetic

README.md
I have added the package definition in https://github.com/NixOS/nixpkgs/pull/382795.
I hope this will make it easy to use by visitors without the build step. A binary cache of Nix might be an alternative solution for https://github.com/reubeno/brush/issues/69.
=> docs: add how to use via nixpkgs

brush-core/src/shell.rs, brush-parser/src/arithmetic.rs
In interactive mode, we need to initialize `PS1` and `PS2` (if unset).
Some profile/rc scripts look at the existence of `PS1` as a signal that the shell is running interactively.
=> fix: default PS1 and PS2 in interactive mode

brush-core/src/shell.rs, brush-shell/tests/cases/extended_tests.yaml
Ensure that, for example, `[[ -e '' ]]` does *not* return 0.
The trouble here is that `Shell::get_absolute_path()` had returned a valid, absolute path when given a `Path` constructed from `""`. This fixes that at the root by explicitly checking for a `Path` whose `.as_os_str()` is empty.
=> fix: correct path tests on empty strings

brush-interactive/src/reedline/prompt.rs
Use plain "reset" color for default prompt color.
=> fix: reset default prompt color

brush-core/src/arithmetic.rs, brush-core/src/extendedtests.rs, brush-core/src/interp.rs, brush-core/src/shell.rs, brush-shell/tests/cases/builtins/ps4.yaml
This PR calls `expand_prompt_var()` on the contents of PS4 within `trace_command()`.  The addition necessitates `trace_command()` become `async` and calls to it use `await`.  A new test case checks expansion against an oracle.
=> Expand contents of PS4 when tracing

brush-core/src/builtins/command.rs, brush-core/src/commands.rs, brush-core/src/interp.rs, brush-core/src/shell.rs, brush-core/src/sys/stubs/fs.rs, brush-core/src/sys/unix/fs.rs, brush-shell/tests/cases/builtins/command.yaml
Rebases #200 against latest changes in tree + adapts to move platform-specific code under `sys`. Also adds a couple of basic compat tests to cover the functionality.
_Huge credit to @39555 for sorting out the problem and getting this working! I've created this under a separate PR to avoid stomping on the previous branch._
=> feat: implement `command -p`

Cargo.lock, brush-interactive/src/reedline/reedline_shell.rs, brush-shell/Cargo.toml, brush-shell/src/main.rs
This (hopefully) finally makes sure that the output from `brush`'s panic handler (whether it be the Rust default or the one set up by `human_panic`) is readable, even when we panicked in the middle of `reedline` taking input.
In the worst case, when we panic -- say, in the middle of displaying the completion menu as happens in #406 -- the terminal is in raw mode and `reedline::Reedline`'s internal painter has some buffered terminal control sequences that haven't yet flushed. At best, the error output is unreadable because emitting `\n` doesn't reset the terminal's column to 0; at worst, the error output is lost entirely because the aforementioned control sequences get flushed at an inconvenient time and wipe out the output.
To address this, we:
1. Do what many other Rust-based console …
=> fix: improve panic handling output

.github/workflows/ci.yaml, brush-shell/tests/cases/redirection.yaml, brush-shell/tests/compat_tests.rs
* Adds openSUSE/tumbleweed + Azure Linux/3.0.
* Adds nix-based container (commented out); will need to debug through test failures on it.
* Adds logic to compat test harness to OR in additional dirs from the host system's PATH in order to resolve standard POSIX tools
=> test: add more linux distros to test matrix

.github/workflows/ci.yaml, brush-core/src/builtins/command.rs, brush-core/src/builtins/printf.rs, brush-shell/tests/cases/builtins/command.yaml
Also includes targeted changes to get tests passing:
* Preserves original `PATH` when invoking `printf` as an external process.
* Ignores `stderr` on a test that may fail on some OSes.
=> test: enable testing on nixos/nix container image

Cargo.lock, brush-interactive/Cargo.toml
`reedline`: 0.38.0 => 0.39.0
Resolves #406
=> chore: upgrade reedline + other deps

brush-core/src/extendedtests.rs, brush-core/src/patterns.rs, brush-core/src/regex.rs, brush-shell/tests/cases/extended_tests.yaml
Fixes extended test regex matching to always enable multiline mode. This ensures that `.` matches `$'\n'`.
=> fix(regex): enable multiline mode for extended test regexes

brush-parser/src/tokenizer.rs, brush-shell/tests/cases/command_substitution.yaml, brush-shell/tests/cases/list.yaml
Only in arithmetic expressions '#' is a valid token, in other contexts it is treated as a comment, and all following characters will be ignored by the tokenizer.
Closes: #408
=> fix: parse '#' as char only if inside a variable expansion

brush-core/src/completion.rs
Way back when, we naively used out own tokenization to split apart an input line before running through programmable completion. As best we can tell, though, we really just need to do a straightforward split by the delimiters defined in `COMP_WORDBREAKS`.
=> fix: honor COMP_WORDBREAKS in completion tokenization

.devcontainer/Dockerfile, brush-core/src/builtins/complete.rs, brush-shell/tests/cases/builtins/complete.yaml
Fix for `complete` built-in being run with no options, and adds a basic compat test for that usage.
Resolves #434
=> fix: handle complete builtin run without options

brush-core/src/shell.rs
This should help by moving the need to (possibly) convert to a `String` from the call-site to the function itself, which should help with the ergonomics of calling these methods.
=> chore(Shell): use relaxed typing for string input

brush-core/src/shell.rs
* ~~I do use a `.clone()` here, which is probably not ideal, so I am open to suggestions on figuring out how to remove it.~~
* We should consider if we should deprecate `get_env_str` or keep it around as a convenience method.
Closes #436.
=> feat(Shell): add `get_env_var` method for more generic variable returns

brush-core/src/shell.rs, brush-shell/src/brushctl.rs
This will be specifically useful for my cases, where I will be inserting variables and builtins (https://github.com/pacstall/pacstall/wiki/101.1-Variables#built-in-variables) into the environment before I source/run a script, but I'm sure a lot of people wanting to interface with brush will also find it useful.
=> feat(Shell): add methods to add environmental variables and builtins

brush-core/src/builtins/trap.rs, brush-shell/tests/cases/builtins/trap.yaml
When `trap` is invoked with `-` as the first argument, then the next argument is treated as a signal name, and the handlers for that signal are removed.
=> fix(trap): handle '-' unregistration syntax

brush-shell/tests/cases/extended_tests.yaml
I've noticed some of the new extended test tests inconsistently failing on local runs. My suspicion is that two sequential invocations of `touch` *could* leave behind files with identical timestamps.
This change explicitly sets a "2 hours ago" modified date on the file that should appear older--to ensure ordering. The local test failures appeared to be resolved with the change. While I was modifying the tests, I added a test case to ensure correct behavior when `-nt` or `-ot` is provided path operands to files that are guaranteed to have identical timestamps (because it's the same file).
=> test(extended-tests): explicitly set modified date on test files

Cargo.lock, brush-core/Cargo.toml, brush-core/src/interp.rs, brush-interactive/Cargo.toml, brush-parser/Cargo.toml, brush-shell/Cargo.toml, fuzz/Cargo.toml, xtask/Cargo.toml
Updates various crate dependencies to stay closer to upstream latest versions. Most notably, this includes version bumps to `reedline`, `nix`, and `clap`.
=> chore: upgrade dependencies: reedline, nix, clap, thiserror, etc.

Cargo.toml, brush-core/src/builtins/complete.rs, brush-core/src/completion.rs, brush-core/src/expansion.rs, brush-core/src/interp.rs, brush-core/src/openfiles.rs, brush-core/src/regex.rs, brush-interactive/src/reedline/prompt.rs, brush-parser/Cargo.toml, brush-parser/benches/parser.rs, brush-parser/src/arithmetic.rs, brush-parser/src/ast.rs, brush-parser/src/error.rs, brush-parser/src/parser.rs, brush-parser/src/pattern.rs, brush-parser/src/tokenizer.rs, brush-parser/src/word.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_arithmetic.rs, fuzz/fuzz_targets/fuzz_parse.rs, xtask/Cargo.toml
This is a stepping stone toward enabling more checks, and specifically checks around type exporting.
=> chore: enable (and fix) current checks across all workspace crates

brush-core/src/builtins/builtin_.rs, brush-core/src/builtins/factory.rs, brush-core/src/interp.rs, brush-shell/tests/cases/builtins/builtin.yaml
Testing `zoxide` uncovered that the `builtin` builtin wasn't correctly wrapping inner builtins that take declarations (e.g., `declare`). This adds some tests to expose that--and a few other tests--and fixes them by adding a new helper that wraps executing `builtin`. Along the way, some of the command execution code benefited from some minimal simplification.
The logic that specially handles declaration arguments is getting increasingly... special. The next time we find ourselves updating it, we should take a hard look at whether there's a cleaner approach.
=> fix(builtin): fix issues with 'builtin' invoking declaration builtins

brush-core/src/builtins/declare.rs, brush-shell/tests/cases/builtins/declare.yaml
In testing with `fzf`, we found that `brush` complains more noisily when `declare -F` (or `-f`) is asked to find a non-existent function. Apparently this is counted on by some scripts (without suppressing `stderr`) to check for function existence.
=> fix(declare): turn down volume on non-existent functions

brush-core/src/error.rs, brush-core/src/expansion.rs, brush-core/src/variables.rs, brush-shell/tests/cases/arrays.yaml, brush-shell/tests/cases/word_expansion.yaml
Enables expansion of expressions like `${array[-1]}` and `${array:-1}`. Notably, the latter syntax doesn't yield similar behavior with strings.
=> fix(expansion): allow negative subscripts with indexed arrays + slices

Cargo.toml
This should allow us to more aggressively strip information from release binaries, with the cost of losing more symbolic info.
=> chore: separate release and bench profiles

brush-shell/tests/cases/arithmetic.yaml, brush-shell/tests/cases/prompt.yaml
Adds small compat test cases to isolate and reproduce a few recently reported issues:
* `ble.sh` runs into a parse error with a `<<` arithmetic operator in a `(( ... ))` construct being treated as a here-document tag (tracked by #484)
* prompt syntax `\#` not implemented (reported in #471)
* prompt syntax '\!` not implemented (related to #469 feature work)
=> test: add known failing tests for reported issues

Cargo.lock, brush-core/Cargo.toml, brush-core/src/builtins/bind.rs, brush-core/src/error.rs, brush-core/src/interfaces.rs, brush-core/src/interfaces/keybindings.rs, brush-core/src/lib.rs, brush-core/src/shell.rs, brush-core/src/sys.rs, brush-core/src/sys/stubs.rs, brush-core/src/sys/stubs/input.rs, brush-core/src/sys/unix.rs, brush-core/src/sys/unix/input.rs, brush-core/src/sys/wasm.rs, brush-core/src/sys/windows.rs, brush-core/src/trace_categories.rs, brush-interactive/src/interactive_shell.rs, brush-interactive/src/reedline/edit_mode.rs, brush-interactive/src/reedline/mod.rs, brush-interactive/src/reedline/reedline_shell.rs, brush-parser/src/error.rs, brush-parser/src/lib.rs, brush-parser/src/readline_binding.rs, brush-shell/src/events.rs, deny.toml
There's a lot here. Supporting even the most minimal functionality in `bind` required:
* Some `reedline`-specific integration code in `brush-interactive` that lets us add an indirection between `reedline` and the key bindings. This was needed to let us mutate the key bindings at runtime.
* A pattern and interface for us to let the `bind` builtin in `brush-core` "upcall" back to the interactive shell layer for querying and mutating bindings.
* Implementation of this new trait for the `reedline` input backend.
* Parsing the `readline` binding syntax supported by `bind`.
* Translating the key codes referenced in the `readline` binding syntax into the abstract keys that `reedline` allows configuring.
* Implementing `READLINE_LINE` and `READLINE_POINT` handling in the shell.
With this support …
=> feat(builtins): implement basic `bind -x` support

brush-core/src/builtins/bind.rs, brush-core/src/shell.rs, brush-interactive/src/reedline/reedline_shell.rs, brush-shell/src/main.rs, brush-shell/src/shell_factory.rs
Without this change, the `reedline` input backend was registering a key bindings implementation *after* `.bashrc` et al. were processed.
=> fix: allow "bind" usage in .bashrc

brush-core/src/expansion.rs, brush-parser/src/word.rs, brush-shell/tests/cases/prompt.yaml, brush-shell/tests/cases/word_expansion.yaml
The issue tracked in #488 was broader than just prompts--and found multiple bugs:
* We were missing some test coverage for a broader form of prompt-expanding.
* We only correctly parsed backquoted commands in containing double-quoted strings if the former started strictly at the start of the latter.
* Ditto for single-quoted strings.
The fixes entail correcting the "stop" conditions for the grammar rules tracking the bodies of the quoted strings.
There's still an unresolved issue of `@P`-expansion needing to word-expanding the prompt-expanded result. That will need to be resolved in a separate PR.
Resolves #488
=> fix(expansion): fix issues parsing backquoted commands nested in single/double-quoted strings

brush-core/src/builtins/break_.rs, brush-core/src/builtins/continue_.rs
`default_value` is for types that can be converted into a `String`, which can be expensive, but `default_value_t` is for stack-allocated types and should be a less expensive to use.
At the level that you use `default_value`, it won't get us that much more performance, but it's still worth it.
#490 does the ones for `mapfile`.
=> fix(break,continue): use `default_value_t` for flag values

brush-core/src/builtins.rs, brush-core/src/builtins/bind.rs, brush-core/src/builtins/complete.rs, brush-core/src/builtins/enable.rs, brush-core/src/builtins/exec.rs, brush-core/src/builtins/hash.rs, brush-core/src/builtins/kill.rs, brush-core/src/builtins/read.rs, brush-core/src/builtins/set.rs, brush-core/src/builtins/wait.rs
* Updates `name_value` for various builtin options
* Opts for more compact help output for named options
=> fix(help): better compact argument help

brush-interactive/src/reedline/reedline_shell.rs
Per default readline bindings, `Ctrl+_` should map to "undo". To coerce `reedline` to do this, it seems we need to request that it map `Ctrl+7`.
_There's risk that this may not work in certain keyboard configurations or terminals; thus far we've tested this in alacritty, Windows Terminal, and VS Code's terminal._
=> fix(input): map Ctrl+_ -> undo

.github/workflows/spelling.yaml, Cargo.toml, brush-core/src/builtins.rs, brush-core/src/builtins/dot.rs, brush-core/src/builtins/eval.rs, brush-core/src/builtins/let_.rs, brush-core/src/builtins/set.rs, brush-core/src/commands.rs, brush-core/src/processes.rs, brush-parser/src/parser.rs, brush-shell/tests/cases/command_substitution.yaml, brush-shell/tests/cases/list.yaml, brush-shell/tests/compat_tests.rs
* Used [typos](https://github.com/crate-ci/typos) to find typos in code base; corrected typos.
* Added appropriate exclusions to `Cargo.toml` for files that shouldn't be checked (`CHANGELOG.md`) and string patterns to allow-list
* Added PR check to run `typos`
=> fix: fix typos + add spell-checking PR check

brush-core/Cargo.toml, release-plz.toml
`release-plz` hit a snag because it builds the crates individually vs. at the workspace level, and that found that there's a required `tokio` feature (`sync`) missing in the `brush-core` crate manifest.
This fixes that issue and updates the `release-plz` config while we're at it.
=> fix: add missing tokio feature to unblock release

brush-interactive/src/completion.rs
For now, we need to suppress the warnings. When building with `--no-default-features`, `brush-interactive` hits a few warnings because completion-related code isn't required (and thus unused/dead).
Once we're past the impending release, we need to look back at this and appropriate tag the code as being conditional on the features that actually require it.
=> fix: suppress warning when building with --no-default-features

README.md, brush-core/src/builtins/factory.rs, brush-shell/tests/cases/builtins/typeset.yaml
`typeset` is a full synonym of `declare`, but it wasn't being correctly registered as a builtin that can take complex declarations.
This fixes the registration and at least adds a "lights on" compat test for it.
=> fix(typeset): mark typeset as a declaration builtin

brush-parser/src/tokenizer.rs, brush-shell/tests/cases/word_expansion.yaml
While running the `bash` test suite, we identified that `brush`'s tokenization process was causing `$( (...) )` to be treated as an arithmetic expression (incorrect) instead of a command substitution with a nested subshell (correct).
This change adds a targeted fix that lets parsing of a command substitution preserve the whitespace in its body during tokenization.
=> fix(tokenizer): correctly treat $( (...) ) as a cmd substitution

brush-parser/src/word.rs, brush-shell/tests/cases/word_expansion.yaml
Ensure that a trailing backslash in a backquoted command substitution is correctly handled.
=> fix(backquote): correct backslash handling

brush-parser/src/arithmetic.rs, brush-shell/tests/cases/arithmetic.yaml
Fixes, for example, `$(( - 10 ))` (where there's space characters between the `-` and the literal).
=> fix(arithmetic): permit space after unary operator

.github/workflows/ci.yaml
These are largely focused on avoiding references to template expansions in the body of a `run:` property.
=> ci: fix pedantic warnings from newer zizmor release

brush-shell/Cargo.toml
Adds metadata to `Cargo.toml` that will allow `cargo-binstall` to find the officially released binaries for `brush`.
=> feat: enable cargo-binstall to work with brush

Cargo.lock, brush-parser/Cargo.toml, brush-parser/src/ast.rs, brush-parser/src/prompt.rs, brush-parser/src/readline_binding.rs, brush-parser/src/tokenizer.rs, brush-parser/src/word.rs
In preparation for snapshot-based testing, this cherry-picks (and adapts) @39555's work from #265 to derive `Eq`, `PartialEq`, and `serde::Serialize` on all AST and parsed types -- but for `cfg(test)` only. There's not presently any reason to derive these for `release` builds.
=> test(parser): enable serde::Serialize on AST et al. for test targets

brush-core/src/shell.rs
This allows reading input scripts from bytes, in addition to the existing string functionality.
=> Allow reading a script from bytes

Cargo.lock, brush-parser/Cargo.toml, brush-parser/src/ast.rs, brush-parser/src/lib.rs, brush-parser/src/parser.rs, brush-parser/src/snapshot_tests.rs, brush-parser/src/snapshots/brush_parser__parser__tests__parse_case.snap, brush-parser/src/snapshots/brush_parser__parser__tests__parse_case_ns.snap, brush-parser/src/snapshots/brush_parser__parser__tests__parse_function_with_pipe_redirection-2.snap, brush-parser/src/snapshots/brush_parser__parser__tests__parse_function_with_pipe_redirection.snap, brush-parser/src/snapshots/brush_parser__parser__tests__parse_program.snap, brush-parser/src/snapshots/brush_parser__parser__tests__parse_redirection.snap, brush-parser/src/snapshots/brush_parser__word__tests__parse_arithmetic_expansion.snap, brush-parser/src/snapshots/brush_parser__word__tests__parse_arithmetic_expansion_with_parens.snap, brush-parser/src/snapshots/brush_parser__word__tests__parse_backquoted_command.snap, brush-parser/src/snapshots/brush_parser__word__tests__parse_backquoted_command_in_double_quotes.snap, brush-parser/src/snapshots/brush_parser__word__tests__parse_command_substitution.snap, brush-parser/src/snapshots/brush_parser__word__tests__parse_command_substitution_with_embedded_extglob.snap, brush-parser/src/snapshots/brush_parser__word__tests__parse_command_substitution_with_embedded_quotes.snap, brush-parser/src/snapshots/brush_parser__word__tests__parse_extglob_with_embedded_parameter.snap, brush-parser/src/tokenizer.rs, brush-parser/src/word.rs, brush-shell/tests/compat_tests.rs
Switches parser tests to use `insta` crate for snapshot-based testing using RON serialization (for now). The best way to update/review snapshot changes is the `cargo insta` tool.
Also adds not-yet-enabled test code that can do snapshot testing of the parser using the scriptlets in all the YAML test cases.
_Credit to @39555 for path-finding via #265._
Resolves #254
=> test(parser): start using insta crate for snapshot-testing parser

brush-parser/src/parser.rs, brush-parser/src/snapshots/brush_parser__parser__tests__parse_here.snap, brush-parser/src/snapshots/brush_parser__parser__tests__parse_here_doc_with_no_trailing_newline.snap, brush-parser/src/snapshots/brush_parser__tokenizer__tests__tokenize_here_doc-2.snap, brush-parser/src/snapshots/brush_parser__tokenizer__tests__tokenize_here_doc-3.snap, brush-parser/src/snapshots/brush_parser__tokenizer__tests__tokenize_here_doc-4.snap, brush-parser/src/tokenizer.rs, brush-shell/tests/cases/here.yaml
This fixes the tokenizer to handle a here document being terminated by the final tag, immediately followed by an EOF (rather than a newline).
_Huge credit to @mati865 for finding the issue, identifying a targeted fix, and sharing it out._
Resolves #547
=> fix(tokenizer): correctly handle here docs terminated by EOF

Cargo.lock, brush-core/Cargo.toml, brush-core/src/builtins.rs, brush-core/src/builtins/factory.rs, brush-core/src/builtins/printf.rs, brush-core/src/error.rs, brush-core/src/expansion.rs, brush-shell/tests/cases/builtins/printf.yaml
Today, apart from a few targeted special-cases, `brush`'s implementation of the `printf` builtin is a thin wrapper over `/usr/bin/printf` (which it implicitly takes a runtime dependency on). This is debt that we're eager to address.
This replaces the implementation with a wrapper over `uucore`'s `printf` implementation, from the Rust-based `uutils/coreutils` project. It does add that dependency, which we anticipate will slightly increase our binary size, but bring us much better performance, portability, and fidelity than we have today.
We also introduce a set of tests that were used to pin preexisting behavior and confirm that we're no worse, functionality-wise, with the changes.
_(Aside: we first tried a few other Rust-based implementations first, notably among them being the `sprintf` …
=> feat(printf): replace printf impl with uucore wrapper

brush-core/src/sys/unix/signal.rs, brush-core/src/traps.rs
This doesn't actually implement the trap but ensures that it's not considered "invalid" when specified to `trap`.
=> fix(traps): add stub definition for RETURN trap

brush-core/src/commands.rs, brush-shell/tests/cases/functions.yaml
`ble.sh` (and others) rely heavily on functions with `/` in their names. This adds a test for this case and fixes the resolution logic in command execution to support them.
=> fix(functions): allow func names to contain slashes

brush-parser/src/tokenizer.rs, brush-shell/tests/cases/arithmetic.yaml, brush-shell/tests/cases/here.yaml
Adds logic to the tokenizer to recognize `(( ... ))` as an arithmetic context, within which `<<` is not indicating a here-document.
_Aside: This is a targeted patch, and motivation for need to improve parsing._
Resolves #484.
=> fix(arithmetic): correct left shift handling

brush-parser/src/word.rs, brush-shell/tests/cases/word_expansion.yaml
Adds some tests, and cleans up the implementation. As an expediency, uses `.rev()` since `.step_by()` can't cope with negative increments.
=> fix(expansion): handle signed numbers in ranges

README.md, brush-core/src/interp.rs, brush-parser/src/ast.rs, brush-parser/src/parser.rs, brush-parser/src/snapshots/brush_parser__parser__tests__parse_function_with_pipe_redirection.snap, brush-parser/src/snapshots/brush_parser__parser__tests__parse_program.snap, brush-shell/tests/cases/redirection.yaml
More correctly handles `>&` cases where expansion is needed, and adds support for `>&-`, `>&N-`, etc.
=> fix(redirection): assorted fixes to redirection

brush-core/src/expansion.rs, brush-parser/src/word.rs, brush-shell/tests/cases/word_expansion.yaml
Fixes parsing and interpreting of parameter transformation expansion with indirection.
=> fix(expansion): correct ${!PARAM@...}

brush-parser/src/word.rs, brush-shell/tests/cases/word_expansion.yaml
Adds onto #561 to fix word-parsing of ANSI-C strings containing escaped single-quote chars.
=> fix(expansion): fix parsing escaped single-quotes in ANSI-C strs

brush-parser/src/arithmetic.rs, brush-parser/src/error.rs, brush-parser/src/lib.rs, brush-parser/src/pattern.rs, brush-parser/src/prompt.rs, brush-parser/src/test_command.rs, brush-parser/src/word.rs
This is a prerequisite to support alternate parsers.
=> Abstract parse errors

brush-parser/src/parser.rs, brush-shell/tests/cases/compound_cmds/case.yaml, brush-shell/tests/cases/compound_cmds/for.yaml
Resolve this issue for `for` and `case`, which was actually predicted a bit by the `TODO` comments but hadn't been resolved.
Also adds test cases to cover.
=> fix(for/case): allow reserved words in for word lists

brush-core/src/shell.rs, brush-shell/tests/cases/builtins/dot.yaml
For compatibility, `.` (or `source`) should only shadow args (e.g., `$@`) from the parent environment when a non-zero number of args were passed. #581 has more details.
Resolves #581
=> fix(dot): only shadow args when provided to `source`

Cargo.lock, brush-shell/Cargo.toml, brush-shell/tests/completion_tests.rs, brush-shell/tests/interactive_tests.rs
Use the `test-with` crate to tag integration test cases that have external dependencies (e.g., on bash-completion, ping, etc.).
This should hopefully mitigate some or all of #429, although we still have work to do to be able to run more of these tests *without* the dependencies in question. It's a first step to making the dependencies more manifest.
=> tests: tag test binary dependencies

brush-shell/tests/cases/builtins/unset.yaml, brush-shell/tests/cases/here.yaml
Adds test cases that reproduce #419, #421, and #497 -- all marked as known failures.
=> tests: add test cases for open issues

.github/workflows/ci.yaml, brush-core/src/builtins/shopt.rs, brush-core/src/builtins/type_.rs, brush-shell/tests/cases/builtins/cd.yaml, brush-shell/tests/cases/builtins/compgen.yaml, brush-shell/tests/cases/builtins/pushd_popd_dirs.yaml, brush-shell/tests/cases/builtins/shopt.yaml, brush-shell/tests/cases/builtins/type.yaml, brush-shell/tests/cases/patterns/filename_expansion.yaml, brush-shell/tests/cases/well_known_vars.yaml, brush-shell/tests/cases/word_expansion.yaml, brush-shell/tests/compat_tests.rs
Mitigates new failures in compat test suite arising from bash `5.3` being available as an oracle.
=> fix: prepare tests to run against bash-5.3

brush-shell/src/args.rs, brush-shell/src/main.rs, brush-shell/tests/cases/basic.yaml
Fixes cases where `brush` is given a script and hyphenated script arguments on the command line, e.g.:
`brush some-script.sh -v`
Without this fix, `brush` consumes the `-v` as part of its own options; with this fix, it passes it along to the script.
=> fix: hyphenated script args

brush-core/src/commands.rs, brush-core/src/shell.rs, brush-shell/tests/cases/command_substitution.yaml
Handle special case for command substitutions where a bare input redirection is used:
> `$(<SOME-FILE)` should behave like `$(cat SOME_FILE)`
=> fix: special case for command subst

.github/workflows/ci.yaml, .github/workflows/codeql.yml, .github/workflows/docs.yaml, zizmor.yml
There now appears to be a `v1` tag that we can pin to in the rust-toolchain git repo.
=> ci: pin rust-toolchain tasks

scripts/run-bash-tests.py
Potential fix for [https://github.com/reubeno/brush/security/code-scanning/8](https://github.com/reubeno/brush/security/code-scanning/8)
To fix the problem, we should remove the assignment to `test_result` on line 111, leaving only the call to `subprocess.run(...)` so that its side effects are preserved. This means replacing `test_result = subprocess.run(...)` with `subprocess.run(...)`. No other changes are necessary, as the result of the subprocess is not used elsewhere. The change should be made in the file `scripts/run-bash-tests.py`, specifically on line 111.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> chore: remove unused global variable

.github/workflows/docs.yaml, Cargo.lock, brush-core/Cargo.toml, brush-shell/Cargo.toml, brush-shell/src/args.rs, brush-shell/src/main.rs, xtask/Cargo.toml, xtask/src/main.rs
_`brush` command line`_
* Upgrades `clap`
* Improves and vertically condenses command-line help
* Improves handling of top-level unknown (or misspelled) command-line options
* Groups related command-line options in subsections
* Adds some basic tests for the custom command-line parsing
_xtask_
* Reorganize `xtask` commands
* Add commands for generating completion scripts for `brush`
=> fix(cmdline): improve error handling for unknown cmdline options

Cargo.lock, brush-shell/Cargo.toml, brush-shell/src/main.rs, brush-shell/tests/integration_tests.rs
* Specifically looks for version/help error kinds coming back from `clap` and differentiates exit code.
* Adds a few basic integration test cases to safeguard against further regression.
Resolves #666
=> fix(cmdline): correct exit code for `--version` + `--help`
