brush-core/src/patterns.rs

fix: correct expansion when PWD is /

---

.github/workflows/ci.yaml
Cargo.lock
Cargo.toml
brush-core/Cargo.toml
brush-shell/Cargo.toml
deny.toml
fuzz/Cargo.toml

Upgrade the held-back crates as part of this (clap et al.)

feat: move MSRV up to 1.75.0

---

brush-core/src/expansion.rs
brush-core/src/shell.rs
brush-core/src/sys/stubs/users.rs
brush-core/src/sys/unix/users.rs
brush-core/src/sys/windows/users.rs
brush-parser/src/word.rs

fix: implement ~USER syntax

---

.github/workflows/ci.yaml
brush-core/src/sys/unix/signal.rs
brush-shell/tests/cases/builtins/cd.yaml
brush-shell/tests/cases/builtins/command.yaml
brush-shell/tests/cases/builtins/dot.yaml
brush-shell/tests/cases/builtins/pushd_popd_dirs.yaml
brush-shell/tests/cases/builtins/pwd.yaml
brush-shell/tests/cases/extended_tests.yaml
brush-shell/tests/cases/prompt.yaml
brush-shell/tests/cases/word_expansion.yaml

* Includes proposed fix for #151 .
* Adjusts some tests (with some TODOs) to get to a good baseline across Linux and macOS; we can improve coverage, debug those TODOs from there.

test: bring up macos testing

---

brush-shell/tests/compat_tests.rs

The compat tests test harness needs to correctly handle `--skipped` when used in conjunction with `--list`. This helps `cargo nextest` figure out how many tests are skipped so it can report it correctly.

test: correctly report skipped tests for nextest

---

Cargo.lock
brush-shell/Cargo.toml
brush-shell/src/main.rs

The handler will encourage filing a GitHub issue.

feat: add a panic handler via human-panic

---

brush-core/src/builtins.rs
brush-core/src/builtins/command.rs
brush-core/src/builtins/factory.rs
brush-core/src/builtins/hash.rs
brush-core/src/builtins/printf.rs
brush-core/src/builtins/type_.rs
brush-core/src/commands.rs
brush-core/src/error.rs
brush-core/src/escape.rs
brush-core/src/lib.rs
brush-core/src/pathcache.rs
brush-core/src/shell.rs
brush-interactive/src/reedline/highlighter.rs
brush-shell/tests/cases/builtins/hash.yaml
brush-shell/tests/cases/builtins/type.yaml

* Implement `hash` builtin
* Update simple command resolution to go through hashed paths (when appropriate)
* Simple optimization for executable lookup in completion code path

feat: implement command hashing

---

brush-core/src/interp.rs
brush-shell/tests/cases/compound_cmds/arithmetic_for.yaml
brush-shell/tests/cases/compound_cmds/for.yaml

fix: correct behavior of break in arithmetic for loop

---

brush-parser/src/parser.rs
brush-parser/src/tokenizer.rs
brush-shell/tests/cases/pipeline.yaml

feat: implement `|&` extension

---

Cargo.lock
brush-interactive/Cargo.toml

chore: upgrade reedline

---

brush-interactive/src/reedline/highlighter.rs

Correct syntax highlighter's handling of multi-byte characters. Short version: use `.chars()` instead of byte-slicing into the `str`.
Resolves #276

fix: correct handling of multi-byte chars in highlighter

---

brush-core/src/builtins/kill.rs
brush-core/src/jobs.rs
brush-core/src/sys/stubs/signal.rs
brush-core/src/sys/unix/signal.rs
brush-shell/tests/cases/builtins/kill.yaml

* Add support for `-<sigspec>` option
* Fill out basic implementation for `-n` and `-s`
* Add a few basic test cases

feat(builtins): implement more of kill builtin

---

brush-core/src/variables.rs
brush-shell/tests/cases/arrays.yaml
brush-shell/tests/cases/builtins/declare.yaml
brush-shell/tests/cases/variables.yaml

Adds a handful of test cases and fixes for array and scalar integer variables (i.e., variables with the `i` attribute on them).

fix(variables): more correct handling of integer variables

---

brush-parser/src/parser.rs
brush-shell/tests/cases/arrays.yaml

fix: allow newline in empty array assignment

---

brush-shell/tests/compat_tests.rs

Extends `brush-compat-tests` to honor `--skip`, e.g.:
We still need a better way to segment our integration tests and make their dependencies evident, but this was a clear gap in brush-compat-tests. There's additional standard args implemented by libtest not being honored; for the meantie, we'll continue to cross those bridges as we come to them.
 
Discussed in #429

test: implement --skip in brush-compat-tests harness

---

README.md

Showing some love for the Arch users :D

docs: Add instructions for installing from the AUR

---

brush-core/src/extendedtests.rs
brush-core/src/sys/fs.rs
brush-core/src/sys/stubs/fs.rs
brush-core/src/sys/unix/fs.rs
brush-core/src/variables.rs
brush-shell/tests/cases/extended_tests.yaml

Adds:
* `-R`
* `-ef`
* `-nt`
* `-ot`

feat(apply_unary_predicate_to_str): implement `-R` operand

---

brush-core/src/shell.rs

This should loosen the constraints on passing parameters to these functions so that:
```rs
shell
.run_script(
&PathBuf::from("/home/elsie/Projects/libpacstall/examples/test.sh"),
vec!["foo", "bar"].into_iter(),
)
.await?;
```
Can look like:
```rs
shell
.run_script(
"/home/elsie/Projects/libpacstall/examples/test.sh",
vec!["foo", "bar"].into_iter(),
)
.await?;
```
Taking https://doc.rust-lang.org/std/fs/fn.read_to_string.html as a reference.

ref(Shell): turn `&Path` parameters into `AsRef<Path>`

---

README.md
brush-core/src/builtins/bind.rs
brush-core/src/builtins/declare.rs
brush-core/src/builtins/factory.rs
brush-core/src/builtins/read.rs
brush-core/src/builtins/unimp.rs
brush-core/src/commands.rs
brush-core/src/completion.rs
brush-core/src/error.rs
brush-core/src/interp.rs
brush-core/src/jobs.rs
brush-core/src/regex.rs
brush-core/src/sys/stubs/terminal.rs
brush-core/src/sys/unix/users.rs
brush-core/src/trace_categories.rs
brush-interactive/src/completion.rs
brush-shell/src/args.rs
brush-shell/src/brushctl.rs
brush-shell/src/events.rs
brush-shell/src/main.rs
brush-shell/tests/cases/builtins/alias.yaml

* Minor updates to readme
* Adds new unimplemented error that can track and report on associated GitHub issue
* Tie in unimplemented log messages with event pattern
* Allow disablement of unimplemented errors via `--disable-event=unimp`

chore: better log + connect unimpl functionality with GH issues

---

brush-core/src/shell.rs
brush-shell/tests/cases/well_known_vars.yaml

This captures the issue described by #479. Once the test passes we can close out that issue.

test: add compat test for $_ (not yet passing)

---

brush-core/src/builtins/factory.rs
brush-shell/tests/cases/builtins/mapfile.yaml

feat(mapfile): Register also as readarray

---

brush-core/benches/shell.rs
brush-core/src/builtins/export.rs
brush-core/src/commands.rs
brush-core/src/error.rs
brush-core/src/functions.rs
brush-core/src/interp.rs
brush-core/src/shell.rs
brush-parser/src/parser.rs
brush-shell/tests/cases/builtins/export.yaml
brush-shell/tests/cases/functions.yaml

* Implements `export -f`
* Implements `export -n`
* Implements serialization/deserialization of exported functions via `BASH_FUNC_<name>%%` variables
Resolves #489

feat(funcs): implement function exporting/importing

---

README.md

Also applies minor reformatting to readme headings.

docs: add discord invite to readme

---

Cargo.lock
brush-core/Cargo.toml
brush-core/src/builtins.rs
brush-core/src/builtins/factory.rs
brush-core/src/builtins/ulimit.rs
brush-shell/tests/cases/builtins/ulimit.yaml
rustfmt.toml

Implement ulimit

---

brush-core/src/shell.rs
brush-shell/src/main.rs
brush-shell/tests/compat_tests.rs
brush-shell/tests/integration_tests.rs

Resolves #530
I wasn't sure how to add appropriate tests for this feature. For now, I've ensured that if there's a major mistake, the integration tests will fail early.

feat(env): introduce brush specific variable

---

.github/workflows/ci-reports.yaml
.github/workflows/ci.yaml
.github/workflows/workflow-checks.yaml
zizmor.yml

Adopts [zizmor](https://github.com/zizmorcore/zizmor) for checking our workflow YAMLs.

ci: enable checks against workflow yaml

---

scripts/run-bash-tests.py

Simpler helper script that requires the bash test suite to have been separately acquired.

test: work-in-progress script to run bash test suite

---

.devcontainer/devcontainer.json
.devcontainer/install-rust-tools.sh

Add TOML extension + preinstall `cargo nextest`

chore: add some tools to devcontainer

---

.github/workflows/cd.yaml
brush-shell/about.hbs
brush-shell/about.toml

Publish license notices as part of CD flow.

ci: publish license notices
